### ISSUE TITLE
[BETA] Some non-ascii characters are not rendered in columns of the declension menu

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1037]
Polyglot version: Windows BETA from 19th November 2021 (latest as of writing this)

Unrendered characters: `ě í ů ý č ď ň ř š ť ť` (and probably more I didn't test)
They are rendered properly when displayed as row and tab names. Seems to be unaffected by changing fonts.

Bug:
![bug1](https://user-images.githubusercontent.com/67415128/142723278-919361fe-399b-4d1a-bbe5-287c4ea7ba4c.png)
Declension:
![bug2](https://user-images.githubusercontent.com/67415128/142723279-c28ceb2c-d448-4e17-a76d-d1aba63c155d.png)
(the "2" declension contains only regular characters and is there in order to be possible to force the broken declension names into columns)

**Comment by DraqueT** [comment]
As with the other bug, I appreciate the detailed writeup!

**Comment by TrapinchO** [comment]
Polyglot version: Windows BETA from 22th November 2021 (latest as of writing this)
Still not rendered.

**Comment by DraqueT** [comment]
Ahh, didn't realize you would be retesting that quickly! I hadn't yet built a new version up to the public beta. Just did so now, so it should be working in the latest available.

**Comment by TrapinchO** [comment]
> Ahh, didn't realize you would be retesting that quickly! I hadn't yet built a new version up to the public beta. Just did so now, so it should be working in the latest available.
Doesn't seem to be the case, sadly.  Just tested it. Downloaded the latest beta version and build date say 22th November.
Bugs still appears, of course.

**Comment by DraqueT** [comment]
It's really weird that the newer version wasn't linked correctly, but worked later for you here... I literally did nothing to fix that between the time when you last said it wasn't working and when it began working for you. Might need to look into that.
