### ISSUE TITLE
Grammar Manager bugs

### ISSUE THREAD

**Issue by rcochrane55** [DraqueT/PolyGlot#1166]
DEVELOPER TEXT
Broken things:
- [x] The horizontal size of the text window goes crazy sometimes
- [x] Resizing text with Conlang font just does not work
- [x] Look into copy/paste problems (copying into grammar section (make sure clipboard isn't being cleared when opening grammar manager))
- [x] Black box problem when copying into PolyGlot from Word
- [x] Selectability issues of text within grammar manager (see below)

ORIGINAL TEXT
I don't know if it's just my installation because I don't see any issues that mention it (though I have tried repairing and reinstalling), but for a while now the text editor in the grammar section has been broken on my machine. some sections of text work as intended, while some lines run off the right side of the page and and I can't scroll over and look at them, can't place my cursor within the line and edit within it, can't remove tabs at the start of the line, and more. I also can't seem to copy and paste into the grammar section from some locations outside of polyglot (when I do I just get a big black block instead of text). I tried copying all the text from a section, deleting it, and then copying it back in from microsoft word, which absolutely did not fix the problem because then I couldn't even see the text. However, I can copy in text from a pdf of the language, but the pasted text then suffers from the same bizarre bugs that plague the grammar section already. 

some lines in the grammar section will not format properly and are unselectable, and when I use the arrow keys to try and navigate my cursor through them each character I move over turns invisible. Sometimes trying to eliminate space between two lines of text causes the lines to be superimposed over each other in an unreadable mess. Deleting text and retyping it also doesn't help because the retyped text ends up suffering from the same or similar problems. This is preventing me from reworking the grammar of my conlang because the text editing features I need to update and fix it are completely broken.

**Comment by DraqueT** [comment]
Could you send me a copy of the file that you're seeing this with? Email is just draquemail@gmail.com . I appreciate that you're taking the time to report these bugs. That's the only way I know that I need to get them fixed! :3

I suspect that it is a real bug and not your installation, as PolyGlot should run virtually identically more or less everywhere.

The whole Grammar section text editor is something that I really do need to replace wholesale. I wrote the whole system from scratch rather than just using a prebuilt solution, and this is the result. I'll need to find a way to convert from one to the other when I do so as well. X|

**Comment by rcochrane55** [comment]
Sure, I'll get it to you when I'm next at my PC. Also, after I submitted this, I checked an old deprecated version of the file and it has the same problems, as do new files I create. so it does seem like there's something going on beyond just this file or my installation.

**Comment by DraqueT** [comment]
I'm going to be working to correct all bugs in this section before the 4.0 release, but the overhaul is going to be a ways off.

**Comment by DraqueT** [comment]
@rcochrane55 

I have corrected all of the problems here as I have been able to see them, but do you have any example files where any/all of these bugs exhibited themselves? I would definitely like to double check that I have cleaned up all of the issues before release.

**Comment by DraqueT** [comment]
As a note, this will be reopened if any of these issues persist.

**Comment by rcochrane55** [comment]
> @rcochrane55
> 
> I have corrected all of the problems here as I have been able to see them, but do you have any example files where any/all of these bugs exhibited themselves? I would definitely like to double check that I have cleaned up all of the issues before release.

The bugs I initially reported still persist in my main file. I'll email it to you for you to double check.
