### ISSUE TITLE
illegal clusters doesn't work

### ISSUE THREAD

**Issue by dangduomg** [DraqueT/PolyGlot#1210]
as can be seen here, word tla is still generated despite having a tl cluster (which is illegal)
![image](https://user-images.githubusercontent.com/85876662/189515449-b4bc3225-6f0c-4cee-9d39-2fbdec3717ab.png)

**Comment by DraqueT** [comment]
Heyo, thank you for taking the time to make feedback here! 

I believe this is something which is fixed in the newest beta version of PolyGlot. Check it out at the link below! I am hoping to make an official release within the next few weeks. : )

**Comment by DraqueT** [comment]
Closing as I didn't hear anything back here. Please comment to reopen if this is still an issue.

**Comment by AliziaKaline** [comment]
Hi. Definitely still an issue (v3.5.1). Illegal clusters have absolutely no effect.
