### ISSUE TITLE
Cannot remove declension type from part of speech

### ISSUE THREAD

**Issue by JGantts** [DraqueT/PolyGlot#1314]
Despite closing and reopening the PolyGot program, I cannot remove Definiteness from the declension types of Verb.

MacOS Ventura 13.2.1

[Kauvi'ali_before pruning_202307271043.pgd.zip](https://github.com/DraqueT/PolyGlot/files/12185359/Kauvi.ali_before.pruning_202307271043.pgd.zip)

**Comment by DraqueT** [comment]
Thank you for reporting this! I will get this corrected and let you know when a beta with the fixed behavior is available.

**Comment by DraqueT** [comment]
Please try downloading the newest beta. I am not currently able to reproduce this, and I believe that this behavior might have been corrected in a fix since the last release.

**Comment by Sinfaen** [comment]
I am also unable to replicate using the beta. @JGantts I will close this issue in about a week unless you're still seeing the issue
