### ISSUE TITLE
Font size in menu options not functioning

### ISSUE THREAD

**Issue by Feainn** [DraqueT/PolyGlot#751]
UPDATE:
The font size option in the menu is neither being respected properly nor saving/loading with PolyGlot.ini properly. This must be corrected.

ORIGINAL USER TEXT:
Hi! First off, amazing program.
There is just this one thing... the font size is too small! My head aches so bad after a while. When I go to Lang Properties > Conlang Font and select a bigger size and then press "ok", nothing happens. If I click on "COnlang Font" again, the size is still 12. Such a pity I literally cannot use it because of how small it is...

**Comment by DraqueT** [comment]
Heyo! A few questions. First, are you opening PolyGlot via the frontend? Java 9 has a bug that normally prevents it from scaling properly on higher rest monitors. Using the frontend should alleviate the issue. Second... I'll definitely look into the font size issue you mention here! Something might have broken in this last update.

Thanks for taking the time to send in a bug report! And I'll get this working for you/get you a beta if need be. ^^

**Comment by Feainn** [comment]
Hey :)
Forgive my ignorance, what does "frontend" mean?
And no, thank **_you_** for taking the time to give us such a pretty program

**Comment by DraqueT** [comment]
PolyGlot will open if you double click PolyGlot.jar or PolyGlot.exe. If you open it using the jar file on Windows, everything will display as very tiny. Opening it via the exe file corrects this. It's a problem that will go away entirely once I finish the Java 12 port of the program.

If that doesn't solve the problem let me know. Like I said, the menu font ignoring the option setting is definitely a bug I need to fix anyhow.

**Comment by Feainn** [comment]
Ah, yes, I tried both ways and the problem still occurs. I also noticed I cannot scroll down the Lang Properties tab, which prevents me from checking/unchecking some features such as "Local Word Lex Display".

Off topic, do you accept donations?

**Comment by DraqueT** [comment]
DPI problems are very common with Java 8 programs, unfortunately. I'm
working to complete PolyGlot 3.0, which will be java 12, and do away with
problems like that entirely. Glad to know that you've found a workaround,
even if it's not a perfect one. Def toss me another email if you need
anything else. ^^

- Draque

**Comment by DraqueT** [comment]
@Feainn If this is something still troubling you, let me know and I can get you a beta copy of PolyGlot 3.0 in which this is fixed.

**Comment by Feainn** [comment]
Hello :)
Sorry for my late reply... yes, I'm still having issues with the font size :(

**Comment by DraqueT** [comment]
No worries! And you can check out the newest Windows beta here: https://drive.google.com/file/d/1Dbd4cpPUGGZ5_zVuzllXdwrWc77QEL93/view?usp=sharing

If you're using a different OS, let me know and I'll toss you the link to that. I'm just getting around to revamping the system that automatically uploads builds of betas every time I make a new revision. ^^
